title: Bogdan Adam's Blog
description: Test automation; Traveling; Sport
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://bogdan-adam.github.io/
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Bogdan Adam
author-img: bogdan-adam-profile.jpg 
about-author: I am a software engineer passionate about test automation, sport and traveling. This is a personal blog in which I write about stuff that sparks my interest.
social-facebook: bogdan.adam.921
social-linkedin: bogdanadam
social-github:  bogdan-adam
social-twitter: adambogdan1993
social-email: bogdan.adamj@gmail.com

# Disqus
discus-identifier: bogdan-adam

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 5
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
