title: Bogdan Adam's Blog
description: Test automation; Traveling; Sport
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: Bogdan Adam's Blog
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Bogdan Adam
author-img: bogdan-adam-profile.jpg 
about-author: I am a software engineer passionate about test automation. 
social-facebook: https://www.facebook.com/bogdan.adam.921
social-linkedin: https://www.linkedin.com/in/bogdanadam/
social-github:  https://github.com/bogdan-adam
social-twitter: https://twitter.com/adambogdan1993
social-email: bogdan.adamj@gmail.com

# Disqus
discus-identifier: Bogdan Adam

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 5
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
